### ISSUE TITLE
Loading medication ontology with Oracle sqlldr results in error "column C_TOOLTIP. second enclosure string not present"

### ISSUE THREAD

**Issue by njgraham** [SCILHS/scilhs-ontology#10]
Command:
`ORACLE_SID=ORCL sqlldr <user>/<password> control=PCORNET_MED.ctl data=PCORNET_MED.TXT bad=PCORNET_MED.bad log=PCORNET_MED.log errors=10000`

Errors from sqlldr log file (nearly all the rows):
`Record 1: Rejected - Error on table BLUEHERONMETADATA.PCORNET_MED, column C_TOOLTIP. second enclosure string not present`

The control file I'm using is attached (changed to .txt since oddly github only allows specific extensions).

[PCORNET_MED_CTL.txt](https://github.com/SCILHS/scilhs-ontology/files/153544/PCORNET_MED_CTL.txt)

**Comment by njgraham** [comment]
I found that though the medication ontology file had Windows line endings (\r\n), there were Unix line endings (\n) within the tooltip colums.  This caused sqlldr to throw the error.  

As a workaround, I wrote a script to remove the line endings within quoted fields in the .csv and that allowed the ontology to be loaded via sqlldr.  See [njgraham/scilhs-ontology 0a87637](https://github.com/njgraham/scilhs-ontology/commit/0a8763762f8377b5c4ed33f0892a3f71bfc34b43)

**Comment by Zabeus** [comment]
I encountered the same issue with SQL Server script. PCORNET_MED.txt had to be modified before loading.

**Comment by jklann** [comment]
Thank you! I'd also written such a script but it must have missed the \n ... I'll update the ontology on next release...

**Comment by jklann** [comment]
It appears I've fixed this, as I do not see it anymore
