### ISSUE TITLE
PCORI_BASECODE incorrect for some principal discharge diagnosis flags

### ISSUE THREAD

**Issue by njgraham** [SCILHS/scilhs-ontology#11]
The PCORI_BASECODE values are inconsistent with the [CDM v3 specification](http://www.pcornet.org/wp-content/uploads/2014/07/2015-07-29-PCORnet-Common-Data-Model-v3dot0-RELEASE.pdf] for "Principal", "Secondary", and "Unable to classify" for the principal discharge diagnosis flag (PDX).

When running SCILHS/i2p-transform, I get values like '1' and '2' in my Diagnosis table rather than 'P' or 'S'.

The following ...

    select c_fullname, c_name, c_basecode, pcori_basecode 
    from "&&i2b2_meta_schema".pcornet_diag 
    where c_fullname like '\PCORI_MOD\PDX\%'
    and c_name in ('Principal', 'Secondary', 'Unable to classify');`

...yields

    \PCORI_MOD\PDX\S\	Secondary	2	2
    \PCORI_MOD\PDX\X\	Unable to classify	0	0
    \PCORI_MOD\PDX\P\	Principal	DiagObs:PRIMARY_DX_YN	1

**Comment by jklann** [comment]
Fixed in upcoming 2.1 release.
