### ISSUE TITLE
Ontology file import - literal "NULL" converted to actual null

### ISSUE THREAD

**Issue by ariedl** [SCILHS/scilhs-ontology#13]
This may be database/upload client specific.  Using Oracle SQL Developer backed by Oracle 11g literal "NULL" values were converted to actual nulls.  Lori's suggestion of Adding a leading space: " NULL" resulted in successful literal upload.

**Comment by jklann** [comment]
I am fixing this in demographics and enrollment. Let me know if I missed any other tables in which it appears.
