### ISSUE TITLE
meds and labs in scope now? README out of date?

### ISSUE THREAD

**Issue by dckc** [SCILHS/scilhs-ontology#20]
The README says:
> What's not in the ontology?
> 
> Medications, labs, and patient-reported outcomes will be included in CDM v2.1

But I can see pcornet_lab and pcornet_med in MetadataFiles.

**Comment by jklann** [comment]
Yes, it is out of date. I'll fix it soon. Thanks.

**Comment by jklann** [comment]
README updated.
