### ISSUE TITLE
Same Dx and PX c_basecodes

### ISSUE THREAD

**Issue by sguptawustl** [SCILHS/scilhs-ontology#26]
Both Pcornet_Proc and Pcornet_Diag ontology table have the following c_basecodes:
ICD10:B00, ICD10:B01, ICD10:B02, ICD10:B03, ICD10:B04, ICD10:B20, ICD10:B30, ICD10:B33, ICD10:B34, ICD10:B40, ICD10:B41, ICD10:B42, ICD10:B43, ICD10:B44, ICD10:B50, ICD10:B51, ICD10:B52, ICD10:B53, ICD10:B54, ICD10:B70, ICD10:B80, ICD10:B82, ICD10:B83, ICD10:B90, ICD10:B91, ICD10:B92, ICD10:C01, ICD10:C02, ICD10:C03, ICD10:C05, ICD10:C21, ICD10:C22, ICD10:C23, ICD10:C25, ICD10:C51, ICD10:C71, ICD10:C72, ICD10:C75, ICD10:C76, ICD10:C81, ICD10:C91, ICD10:D00, ICD10:D01, ICD10:D02, ICD10:D70, ICD10:D71, ICD10:D72, ICD10:D80, ICD10:D81, ICD10:D82, ICD10:F01, ICD10:F02, ICD10:F06, ICD10:F07, ICD10:F09, ICD10:F13, ICD10:F14, ICD10:F15

This may cause incorrect counts query results. For example: If Diagnosis code 'ICD10:F15' is queried for then both diagnosis and procedure records will be included in the patient count. Likewise, if Procedure code 'ICD10:F15' is queried.

In genera, diagnosis codes should always be different from procedure codes in the ICD coding system. Please look into this.

**Comment by jklann** [comment]
Thanks Snehil, this has been fixed in version 2.1 which has a new ICD-10 Procedures tree.
