### ISSUE TITLE
dbo.stringpart function doesn't use @delimiter arg

### ISSUE THREAD

**Issue by ConnieZ** [SCILHS/scilhs-ontology#31]
This is a minor issue, I suppose. But the dbo.stringpart function in ontology_utils_mssql.sql script doesn't make use of @delimiter argument. It seems, instead of the '\' it should say @delimeter in the following lines:
`WHILE @num!=@el and CHARINDEX('\', @stringToSplit) > 0`
`SELECT @pos  = CHARINDEX('\', @stringToSplit)`
Please reject this issue, if this is an incorrect assumption. Thanks.

**Comment by jklann** [comment]
Ah ha! You are correct!

**Comment by matthewjoss** [comment]
Fixed in the mssql utility script. Not fixed in oracle yet.
