### ISSUE TITLE
Diagnosis 2.1.2: wacky dimcodes

### ISSUE THREAD

**Issue by jklann** [SCILHS/scilhs-ontology#36]
Non-standard dimcodes snuck into diagnosis 2.1.2.

**Comment by jklann** [comment]
fixed

**Comment by ConnieZ** [comment]
@jklann , could you please clarify what exactly was the problem and how it was fixed? And was it fixed inside https://github.com/SCILHS/scilhs-ontology/tree/master/Ontology/ForUpgradingOnly
