### ISSUE TITLE
pcornet_agetree weird c_dimcode for Age 24

### ISSUE THREAD

**Issue by ConnieZ** [SCILHS/scilhs-ontology#37]
@jklann , we noticed that inside https://github.com/SCILHS/scilhs-ontology/blob/master/Ontology/ForUpgradingOnly/pcornet_agetree.txt file, c_dimcode value for '\PCORI\ENCOUNTER\Age at visit\18-34 years old\24 years old\' is not consistent with the other calculation formulas. For example, for 23 years old it's 
`((select birth_date from PCORI_Dev.dbo.patient_dimension where patient_num = PCORI_Dev.dbo.visit_dimension.patient_num) + (365.25 * 23)-1) AND ((select birth_date from PCORI_Dev.dbo.patient_dimension where patient_num = PCORI_Dev.dbo.visit_dimension.patient_num) + (365.25 * 24)-1)`
But for 24 years old, it's:
`getdate() - (365.25 *25) + 1 AND getdate() - (365.25 * 24) + 1`

Could you please look into that and if necessary adjust the released file? Thank you!

**Comment by jklann** [comment]
Fixed
