### ISSUE TITLE
How are the "D~s1uh" parts of Diagnosis paths computed?

### ISSUE THREAD

**Issue by dckc** [SCILHS/scilhs-ontology#38]
I'm thinking about adopting the SCILHS pcornet diagnosis hierarchy, but I'd like to retain our ability to update our ontologies directly from UMLs. How are the `D~s1uh` parts of Diagnosis paths computed?

```
<key>\\PCORI_DIAG\PCORI\DIAGNOSIS\09\(001-999.99) D~qlur\(460-519.99) D~s1uh\(480-488.99) P~xhpo\(486) Pneumoni~ido6\</key>
<dimcode>\PCORI\DIAGNOSIS\09\(001-999.99) D~qlur\(460-519.99) D~s1uh\(480-488.99) P~xhpo\(486) Pneumoni~ido6\</dimcode>
<tooltip>ICD9CM \ Diseases and injuries \ Diseases of the respiratory system \ Pneumonia and influenza \ Pneumonia, organism unspecified</tooltip>
```

**Comment by lcphillips2** [comment]
The ~s1uh part is computed via the attached SymbolHash java file
[SymbolHash.txt](https://github.com/SCILHS/scilhs-ontology/files/407185/SymbolHash.txt)
 .  The 'D' is the first letter of the c_name.
(Rename the file from '.txt' to '.java') 
Technically what you are seeing above is [(basecode) + c_name] truncated to 14 chars followed by  '~' and the 4-char string returned by SymbolHash code.

**Comment by dckc** [comment]
Thanks for the details.
