### ISSUE TITLE
c_tooltip in pcornet_lab update. Connies Issue #1.

### ISSUE THREAD

**Issue by matthewjoss** [SCILHS/scilhs-ontology#44]
The pcornet_lab table upgrade, had this code:

line 47: update pcornet_lab set c_tooltip=replace(c_fullname,'Renal Function','Electrolytes') where c_fullname like '%\CREATININE\%'

Should that instead be :
update pcornet_lab set c_tooltip=replace(c_tooltip,'Renal function','Electrolytes') where c_fullname like '%\CREATININE\%'

We ran the original code, but while reviewing that just didn't make much sense to replace c_tooltip with data from c_fullname, because now c_tooltip looked different from other c_tooltip values (and none of the c_fullname values contained 'Renal Function', and also currently c_tooltip has lower-case 'function', so the intended replacement didn't occur anyway.

**Comment by jklann** [comment]
Applied this change to the ontology; did not update the migration script, we are not keeping this updated.
