### ISSUE TITLE
c_fullname in pcornet_lab fix. Connies issue #3.

### ISSUE THREAD

**Issue by matthewjoss** [SCILHS/scilhs-ontology#46]
In pcornet_lab c_fullname for Version row is actually "\PCORI\LAB_RESULT_CM\Version\", so the setversion() function doesn't work on it, because it's case-sensitive (defined in ontology-utils-mssql.sql). The two solutions would be a) make the c_fullname consistent with other tables ('VERSION'), or b) adapt the ontology-utils-mssql script to disregard case when updating the Version c_name.

If these assumptions above are correct, we will go ahead and make the corrections on our side, not waiting for official corrections on GitHub, however, perhaps down the road we wish these could be made official, so we are consistent with other sites.

Also, could you please recap what the versions for each pcornet table is going to look like with the latest upgrade? Here's how we believe it should look in the end:

pcornet_demo
2.1.1
pcornet_diag
2.1.1
pcornet_enc
2.1.1
pcornet_enroll
2.1
pcornet_lab
2.1
pcornet_med
2.2
pcornet_proc
2.1
pcornet_vital
2.1

**Comment by jklann** [comment]
MSSQL is by default not case sensitive.

**Comment by jklann** [comment]
Changed the case for the lab version line.
