### ISSUE TITLE
Medication ontology: SHRINE interop below ingredient level?

### ISSUE THREAD

**Issue by dckc** [SCILHS/scilhs-ontology#52]
How did you choose which `RXNORM:` codes to put where in the ontology? Do you expect to be able to do SHRINE queries across multiple sites down to the branded drug pack or even NDC code?

The top 3 levels are clear enough: 2 levels of VA class and then the RxNorm ingredient:
  - cn000 Central Nervous System
    - cn100 Non-opioid analgesics
      - RXNORM:214137 Acetaminophen/caffeine/pyrilamine

But below there, I don't see how things are organized. I see a smattering of generics and branded drugs, and below them, sometimes NDC codes.

We found the same name at two levels, which looked odd:
`RxNorm CUI \ [an000] antineoplastics \ [an500] antineoplastic hormones  \ Tamoxifen \ Tamoxifen 20 mg oral tablet \ Tamoxifen 20 mg oral tablet`
but looking closer, the leaf is  NDC:00054883425 and the folder with the same name is [RXNORM:313195](https://mor.nlm.nih.gov/RxNav/search?searchBy=RXCUI&searchTerm=313195), which is an SCD.

In #14 I see reference to scripts that fill in `pcori_ndc` and `pcori_rxnorm`. Would you please point me to those?

cc @rwaitman, @njgraham, @mprittie
see also [GPC ticket:280](https://informatics.gpcnetwork.org/trac/Project/ticket/280).

**Comment by jklann** [comment]
Yes, it's
* VA Class
   * Ingredient or multi-ingredient
      * SCDs and SBDs
         * [NDC drug if available]
 
The oddly named drug is indeed an SCD with a mapped NDC of the same name. This happened in some cases when we couldn't find a name for the NDC code, so we duplicated the RxNorm name.

@lcphillips2 says: "I agree its awkward .. perhaps the NDC term should be hidden, but then you wouldn’t be able to find the term by NDC code."

**Comment by dckc** [comment]
OK, that answers my question about ontology organization. Thanks...

How about SHRINE interop expectations? If those are not out of scope of this repository... is it expected that every site has all and only the RXNORM and NDC codes provided from this repo? That seems unrealistic. It seems more likely that we could expect all sites to supply the same VA classes and ingredient folders, and SHRINE customers shouldn't expect to be able to query at a finer granularity than that.

**Comment by jklann** [comment]
Thanks Dan. Can you give us a little more information on what would be difficult about mapping to the current SCILHS ontology? Do sites not have many dose-forms, have they already mapped to the ingredient, or something else?

We're feeling that for SHRINE probably ingredient would be ok, but if we move to a deidentifiied data study we'd need more specific RxCUIs. I could believe that NDC's are out-of-scope, since that'd be a bit more work to be inclusive.

**Comment by dckc** [comment]
"for SHRINE probably ingredient would be ok" addresses my question; as it appears we are agreed, I'm closing this. Feel free to re-open to reconsider, of course.

As to the rest...

Our original concern was that we compared KUMC's RXNORM organization with this one and we didn't see much of a pattern in the relationship. Perhaps when we re-organize around ingredient, we will find that we have the same set of SCDs and SBDs below each ingredient, but it seems unlikely.

Also, RxNorm is updated weekly, and the updates are evidently not just fringe things that have no intersection with the bulk of usage. SCDs and SBDs with significant usage are obsoleted remarkably often. (IOU an example or two.)

**Comment by dckc** [comment]
Jim Campbell gave an example that shows ingredient level doesn't suffice: : In adaptable: “Oral Form” is below aspirin ingredient.

I gather he's working with you on a more refined proposal including historical RXNORM codes for interoperability.
