### ISSUE TITLE
DX_ORIGIN has incorrect value in c_facttablecolumn

### ISSUE THREAD

**Issue by sguptawustl** [SCILHS/scilhs-ontology#68]
File(s): upgradeV2toV31.sql, pcornet_diag.txt

Line Number:
upgradeV21toV31.sql: 107 - 124
pcornet_diag.txt: 70-75

Issue: c_facttablecolumn is specified as "sourcesystem_cd"

Resolution: c_facttablecolumn should be specified as "modifier_cd"

**Comment by jklann** [comment]
It actually is designed that way, in case local sites want to use a sourcesystem_cd to demarcate where data comes from. It is unlikely that sites will want to add modify rows for this, but they can feel free to.
